//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaoMinhWebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Nhom> Nhoms { get; set; }
        public virtual DbSet<QuyenTai_NhomThuocChiNhanh> QuyenTai_NhomThuocChiNhanh { get; set; }
        public virtual DbSet<QuyenXem_NhomThuocChiNhanh> QuyenXem_NhomThuocChiNhanh { get; set; }
        public virtual DbSet<NhomThuocChiNhanh> NhomThuocChiNhanh { get; set; }
        public virtual DbSet<PQDONVI_> PQDONVI_ { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoan { get; set; }
    }
}
