//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaoMinhWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhomThuocChiNhanh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhomThuocChiNhanh()
        {
            this.QuyenTai_NhomThuocChiNhanh = new HashSet<QuyenTai_NhomThuocChiNhanh>();
            this.QuyenXem_NhomThuocChiNhanh = new HashSet<QuyenXem_NhomThuocChiNhanh>();
        }
    
        public int id { get; set; }
        public int MaChiNhanh { get; set; }
        public int MaNhom { get; set; }
    
        public virtual Nhom Nhom { get; set; }
        public virtual NhomThuocChiNhanh NhomThuocChiNhanh1 { get; set; }
        public virtual NhomThuocChiNhanh NhomThuocChiNhanh2 { get; set; }
        public virtual PQDONVI_ PQDONVI_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuyenTai_NhomThuocChiNhanh> QuyenTai_NhomThuocChiNhanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuyenXem_NhomThuocChiNhanh> QuyenXem_NhomThuocChiNhanh { get; set; }
    }
}
